# FileHarbor Conda Environment
# For Windows development with Miniconda
#
# Create environment:
#   conda env create -f environment.yml
#
# Activate environment:
#   conda activate fileharbor
#
# Update environment:
#   conda env update -f environment.yml --prune

name: fileharbor

channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.13

  # Core dependencies
  - pip
  - cryptography>=41.0.0
  
  # Development tools
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-asyncio>=0.21.0
  
  # Code quality
  - black>=23.0.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  - isort>=5.12.0
  
  # Documentation
  - sphinx>=7.0.0
  - sphinx-rtd-theme>=1.3.0
  
  # Jupyter (optional, for interactive testing)
  - jupyter>=1.0.0
  - ipython>=8.0.0
  
  # Additional tools
  - ipdb>=0.13.0  # Debugger
  
  # Install package in development mode via pip
  - pip:
    - -e .
